### ISSUE TITLE
Why not copy the file?

### ISSUE THREAD

**Issue by chentsulin** [hemanth/blns#1]
If we copy `blns.json` from Big List of Naughty Strings's repo or use `.gitmodules` or any others, we can keep api more graceful like this: 

``` js
// index.js
module.exports = require('./blns.json');
```

``` js
var blns = require('blns');
// => [ ... ]
```

http request will hurts test performance and repo url maybe changed as time goes on. Bumping version for update will be a good choice.

**Comment by hemanth** [comment]
`.gitmodules` is a good choice given that we keep it in sync with the upstream, PR welcome :+1:

**Comment by bram-dingelstad** [comment]
I made PR for this issue, please check it just to be sure.

**Comment by hemanth** [comment]
@96AA48 Thanks the `submodule` part looks fine, but we need to find a way to keep it in sync always `readme` must be changed and the `package.json`'s `file` section as well. :+1:

**Comment by bram-dingelstad** [comment]
Sorry for my sloppy coding, I changed the code around so that @chentsulin implementation of `require('path/to/blns/json')` is in place as well. Will change readme and package.json in a bit.

**Comment by bram-dingelstad** [comment]
Changed the README and package.json as well, should be ready to merge.

**Comment by chentsulin** [comment]
I think it can be simplified to something like below:

Module:

```js
'use strict';

module.exports = require('./resources/blns.json');
```

And test :

```js
'use strict';

var assert = require('assert');
var blns = require('./');

assert(Array.isArray(blns));
```

Any ideas here?

**Comment by bram-dingelstad** [comment]
Yeah, that seems to do it as well. Should I make the changes and push them @chentsulin ?

**Comment by hemanth** [comment]
Looks fine, but how do we keep it in sync always, maybe using a githook?

``` sh
git submodule foreach 'git fetch origin --tags; git checkout master; git pull' && git pull && git submodule update --init --recursive
```

**Comment by bram-dingelstad** [comment]
I have no experience with things like that, I wish you the best of luck!

**Comment by chentsulin** [comment]
@96AA48 you can feel free to use any ideas I mention above.

**Comment by hemanth** [comment]
Fixed in [v2.0.0](https://github.com/hemanth/blns/releases/tag/v2.0.0) thanks :+1:

**Comment by styfle** [comment]
Won't this easily fall out of date (it looks like it's 2 years behind already)?

**Comment by hemanth** [comment]
What do you suggest?

**Comment by styfle** [comment]
There are a couple options.

1. Implement some sort of automated publish script that always grabs master blns and publishes a new version to npm periodically. Maybe even watch for changes to `minimaxir/big-list-of-naughty-strings` repo which could trigger the publish.
2. Change it back to how it used to work and perform an HTTP request each run. This will never be out of date. I might suggest using [cdn.jsdelivr.net](https://cdn.jsdelivr.net/gh/minimaxir/big-list-of-naughty-strings@master/blns.json) instead of [raw.githubusercontent.com](https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.json) but either should work.
